/*
 * This software is licensed under the terms of the MIT License.
 * See COPYING for further information.
 * ---
 * Copyright (c) 2011-2024, Lukas Weber <laochailan@web.de>.
 * Copyright (c) 2012-2024, Andrei Alexeyev <akari@taisei-project.org>.
 */

#include "texture.h"

#include "../api.h"

#include "util.h"

static SDL_GpuTextureFormat sdlgpu_texfmt_ts2sdl(TextureType t) {
	static const SDL_GpuCompareOp mapping[] = {
		[TEX_TYPE_RGBA_8] = SDL_GPU_TEXTUREFORMAT_R8G8B8A8,
		[TEX_TYPE_RGB_8] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_RG_8] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_R_8] = SDL_GPU_TEXTUREFORMAT_R8,
		[TEX_TYPE_RGBA_16] = SDL_GPU_TEXTUREFORMAT_R16G16B16A16,
		[TEX_TYPE_RGB_16] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_RG_16] = SDL_GPU_TEXTUREFORMAT_R16G16,
		[TEX_TYPE_R_16] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_RGBA_16_FLOAT] = SDL_GPU_TEXTUREFORMAT_R16G16B16A16_SFLOAT,
		[TEX_TYPE_RGB_16_FLOAT] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_RG_16_FLOAT] = SDL_GPU_TEXTUREFORMAT_R16G16_SFLOAT,
		[TEX_TYPE_R_16_FLOAT] = SDL_GPU_TEXTUREFORMAT_R16_SFLOAT,
		[TEX_TYPE_RGBA_32_FLOAT] = SDL_GPU_TEXTUREFORMAT_R32G32B32A32_SFLOAT,
		[TEX_TYPE_RGB_32_FLOAT] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_RG_32_FLOAT] = SDL_GPU_TEXTUREFORMAT_R32G32_SFLOAT,
		[TEX_TYPE_R_32_FLOAT] = SDL_GPU_TEXTUREFORMAT_R32_SFLOAT,
		[TEX_TYPE_DEPTH_8] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_DEPTH_16] = SDL_GPU_TEXTUREFORMAT_D16_UNORM,
		[TEX_TYPE_DEPTH_24] = SDL_GPU_TEXTUREFORMAT_D24_UNORM,
		[TEX_TYPE_DEPTH_32] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_DEPTH_16_FLOAT] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_DEPTH_32_FLOAT] = SDL_GPU_TEXTUREFORMAT_D32_SFLOAT,
		[TEX_TYPE_COMPRESSED_ETC1_RGB] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ETC2_RGBA] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_BC1_RGB] = SDL_GPU_TEXTUREFORMAT_BC1,
		[TEX_TYPE_COMPRESSED_BC3_RGBA] = SDL_GPU_TEXTUREFORMAT_BC3,
		[TEX_TYPE_COMPRESSED_BC4_R] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_BC5_RG] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_BC7_RGBA] = SDL_GPU_TEXTUREFORMAT_BC7,
		[TEX_TYPE_COMPRESSED_PVRTC1_4_RGB] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_PVRTC1_4_RGBA] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ASTC_4x4_RGBA] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ATC_RGB] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ATC_RGBA] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_PVRTC2_4_RGB] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_PVRTC2_4_RGBA] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ETC2_EAC_R11] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_ETC2_EAC_RG11] = SDL_GPU_TEXTUREFORMAT_INVALID,
		[TEX_TYPE_COMPRESSED_FXT1_RGB] = SDL_GPU_TEXTUREFORMAT_INVALID,
	};

	uint idx = t;
	assume(idx < ARRAY_SIZE(mapping));
	return mapping[idx];
}

static SDL_GpuTextureFormat sdlgpu_texfmt_to_srgb(SDL_GpuTextureFormat fmt) {
	switch(fmt) {
		case SDL_GPU_TEXTUREFORMAT_R8G8B8A8: return SDL_GPU_TEXTUREFORMAT_R8G8B8A8_SRGB;
		case SDL_GPU_TEXTUREFORMAT_B8G8R8A8: return SDL_GPU_TEXTUREFORMAT_B8G8R8A8_SRGB;
		case SDL_GPU_TEXTUREFORMAT_BC3:      return SDL_GPU_TEXTUREFORMAT_BC3_SRGB;
		case SDL_GPU_TEXTUREFORMAT_BC7:      return SDL_GPU_TEXTUREFORMAT_BC7_SRGB;
		default: return SDL_GPU_TEXTUREFORMAT_INVALID;
	}
}


