#!/usr/bin/env zsh

export BUILD_DIR=$PWD/build
export MESON_BUILD_ROOT_MACOS_X64=$BUILD_DIR/x64
export MESON_BUILD_ROOT_MACOS_AARCH64=$BUILD_DIR/aarch64
export MESON_BUILD_ROOT_MACOS_X64_COMPILED=$BUILD_DIR/compiled/x64
export MESON_BUILD_ROOT_MACOS_AARCH64_COMPILED=$BUILD_DIR/compiled/aarch64
export MESON_BUILD_ROOT_MACOS_COMBINED=$BUILD_DIR/compiled/combined
export TAISEI_BIN_PATH=./Taisei.app/Contents/MacOS/Taisei

mkdir -p $BUILD_DIR/compiled $MESON_BUILD_ROOT_MACOS_COMBINED
meson setup --native-file=misc/ci/macos-x86_64-build-release.ini --prefix $MESON_BUILD_ROOT_MACOS_X64_COMPILED $MESON_BUILD_ROOT_MACOS_X64
meson setup --cross-file misc/ci/macos-aarch64-build-release.ini --prefix $MESON_BUILD_ROOT_MACOS_AARCH64_COMPILED $MESON_BUILD_ROOT_MACOS_AARCH64

meson install -C $MESON_BUILD_ROOT_MACOS_X64
meson install -C $MESON_BUILD_ROOT_MACOS_AARCH64

cp -a $MESON_BUILD_ROOT_MACOS_X64_COMPILED/ $MESON_BUILD_ROOT_MACOS_COMBINED
lipo -create -output $MESON_BUILD_ROOT_MACOS_COMBINED/$TAISEI_BIN_PATH $MESON_BUILD_ROOT_MACOS_X64_COMPILED/$TAISEI_BIN_PATH $MESON_BUILD_ROOT_MACOS_AARCH64_COMPILED/$TAISEI_BIN_PATH

TAISEI_VERSION=$($PWD/scripts/taiseilib/version.py)
echo $TAISEI_VERSION

$PWD/scripts/macos-gen-dmg.py --universal $BUILD_DIR/compiled/Taisei-$TAISEI_VERSION.dmg $MESON_BUILD_ROOT_MACOS_X64 $MESON_BUILD_ROOT_MACOS_COMBINED
