#version 330 core

// Generated by gen-blur-shader.py. kernel size = 13; sigma = 2.45

#include "interface/standard.glslh"
#include "lib/blur/blur13.glslh"

UNIFORM(1) vec2 blur_resolution;
UNIFORM(2) vec2 blur_direction;

void main(void) {
    fragColor = sample_blur13(tex, texCoord, blur_direction / blur_resolution);
}
