#version 330 core

// Generated by gen-blur-shader.py. kernel size = 25; sigma = 4.25

#include "interface/standard.glslh"
#include "lib/blur/blur25.glslh"

UNIFORM(1) vec2 blur_resolution;
UNIFORM(2) vec2 blur_direction;

void main(void) {
    fragColor = sample_blur25(tex, texCoord, blur_direction / blur_resolution);
}
