
LAYER(BACKGROUND)
LAYER(PLAYER_SHOT)
LAYER(PARTICLE_LOW)
LAYER(ITEM)
LAYER(PLAYER_SLAVE)
LAYER(PLAYER)
LAYER(LASER_LOW)
LAYER(PARTICLE_MID)
LAYER(ENEMY)
LAYER(BOSS)
LAYER(PARTICLE_BULLET_CLEAR)
LAYER(BULLET)
LAYER(LASER_HIGH)
LAYER(PARTICLE_HIGH)
LAYER(PLAYER_FOCUS)
LAYER(OVERLAY)

#undef LAYER
