FROM ubuntu:focal

LABEL maintainer="Alice D. <alice@starwitch.productions>"

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
	apt install -y -qq \
	build-essential \
	libsdl2-dev \
	libogg-dev \
	libopusfile-dev \
	libpng-dev \
	libzip-dev \
	libx11-dev \
	libwayland-dev \
	python3-docutils \
	libwebp-dev \
	libfreetype6-dev \
	python3-pip \
	libzstd-dev \
	git

RUN pip3 install \
	meson==0.63.3 \
	ninja \
	zstandard
